# Generated by Django 5.1.2 on 2024-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
